# Additional build products for the external TouchGFX asset flash.
#
# The linked ELF intentionally contains ExtFlashSection at the virtual address
# 0x90000000 so it can be used to build assets.bin and retain full debug
# symbols. ST-LINK must not try to program that virtual segment, therefore the
# MCU download uses the Intel HEX file generated below.

PYTHON ?= python

secondary-outputs: ../Display_test_prova_internal.hex ../assets.bin ../asset_manifest.bin ../asset_metadata.json ../asset_build_verified.stamp

../Display_test_prova_internal.hex: ../Display_test_prova_programming.elf
	arm-none-eabi-objcopy -O ihex --remove-section=ExtFlashSection "$<" "$@"
	@echo 'Generated internal MCU image: $@'

../assets.bin: Display_test_prova.elf
	arm-none-eabi-objcopy -O binary --only-section=ExtFlashSection "$<" "$@"
	@echo 'Generated external W25Q64 assets: $@'

../asset_manifest.bin: ../assets.bin ../Tools/build_asset_metadata.py
	$(PYTHON) ../Tools/build_asset_metadata.py ../assets.bin ../asset_manifest.bin ../asset_metadata.json

../asset_metadata.json: ../asset_manifest.bin

../Display_test_prova_programming.elf: Display_test_prova.elf ../asset_manifest.bin
	arm-none-eabi-objcopy --update-section AssetExpectedSection=../asset_manifest.bin "$<" "$@"
	@echo 'Generated asset-coupled programming ELF: $@'

../asset_expected_embedded.bin: ../Display_test_prova_programming.elf
	arm-none-eabi-objcopy -O binary --only-section=AssetExpectedSection "$<" "$@"

../asset_build_verified.stamp: ../Display_test_prova_internal.hex ../assets.bin ../asset_manifest.bin ../asset_expected_embedded.bin ../Tools/verify_asset_build.py
	$(PYTHON) ../Tools/verify_asset_build.py --assets ../assets.bin --manifest ../asset_manifest.bin --embedded-manifest ../asset_expected_embedded.bin --internal-hex ../Display_test_prova_internal.hex
	@echo verified > "$@"

clean: clean-external-assets

clean-external-assets:
	-$(RM) ../Display_test_prova_internal.hex ../Display_test_prova_programming.elf ../assets.bin ../asset_manifest.bin ../asset_metadata.json ../asset_expected_embedded.bin ../asset_build_verified.stamp

.PHONY: clean-external-assets
