/*
 * RVA15MD_DisplayDriver.c - Adapted for STM32F401RE (Nucleo-F401RE)
 *
 * Uses HAL instead of LL drivers (no LL enabled on F401 project).
 * Uses polling SPI instead of DMA for simplicity.
 * VSync is generated by TIM11 timer interrupt (no tearing effect pin wired).
 *
 * GPIO mapping (from main.h):
 *   DISP_CS  -> PB6
 *   DISP_DC  -> PC7
 *   DISP_RST -> PA9
 */

#include "stm32f4xx_hal.h"
#include "DCS.h"
#include "main.h"
#include "RVA15MD_DisplayDriver.h"

extern SPI_HandleTypeDef hspi1;

volatile uint8_t isTransmittingBlock = 0;

/* Forward declaration - defined in TouchGFXGeneratedHAL.cpp */
extern void DisplayDriver_TransferCompleteCallback(void);

/* Stub VSync GPIO functions (no debug pin on F401) */
void setVSYNC(void)  {}
void clearVSYNC(void) {}

/* --------------------------------------------------------------------------
 * SPI data width helpers (needed for correct RGB565 byte order)
 * In 16-bit mode the SPI shifts MSB first, so RGB565 words are sent correctly.
 * -------------------------------------------------------------------------- */
static void SPI_SetDataWidth16(void)
{
    while (__HAL_SPI_GET_FLAG(&hspi1, SPI_FLAG_BSY)) {}
    __HAL_SPI_DISABLE(&hspi1);
    hspi1.Instance->CR1    |= SPI_CR1_DFF;
    hspi1.Init.DataSize     = SPI_DATASIZE_16BIT;
    __HAL_SPI_ENABLE(&hspi1);
}

static void SPI_SetDataWidth8(void)
{
    while (__HAL_SPI_GET_FLAG(&hspi1, SPI_FLAG_BSY)) {}
    __HAL_SPI_DISABLE(&hspi1);
    hspi1.Instance->CR1    &= ~SPI_CR1_DFF;
    hspi1.Init.DataSize     = SPI_DATASIZE_8BIT;
    __HAL_SPI_ENABLE(&hspi1);
}

/* --------------------------------------------------------------------------
 * Low-level SPI command/data helpers
 * -------------------------------------------------------------------------- */
static void DisplaySendCommandDataArray(uint8_t command, uint8_t *data, uint32_t size)
{
    HAL_GPIO_WritePin(DISP_CS_GPIO_Port, DISP_CS_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(DISP_DC_GPIO_Port, DISP_DC_Pin, GPIO_PIN_RESET); /* command */
    HAL_SPI_Transmit(&hspi1, &command, 1, HAL_MAX_DELAY);
    if (size > 0U && data != NULL)
    {
        HAL_GPIO_WritePin(DISP_DC_GPIO_Port, DISP_DC_Pin, GPIO_PIN_SET); /* data */
        HAL_SPI_Transmit(&hspi1, data, (uint16_t)size, HAL_MAX_DELAY);
    }
    HAL_GPIO_WritePin(DISP_CS_GPIO_Port, DISP_CS_Pin, GPIO_PIN_SET);
}

static void DisplaySendCommand(uint8_t command)
{
    DisplaySendCommandDataArray(command, NULL, 0);
}

static void DisplaySendCommandData(uint8_t command, uint8_t data)
{
    DisplaySendCommandDataArray(command, &data, 1);
}

/* --------------------------------------------------------------------------
 * Public API
 * -------------------------------------------------------------------------- */
void DisplayDriver_DisplayOn(void)
{
    DisplaySendCommand(DCS_SET_DISPLAY_ON);
    HAL_Delay(10);
}

void Display_OFF(void)
{
    DisplaySendCommand(DCS_SET_DISPLAY_OFF);
    HAL_Delay(10);
}

void Display_Set_Area(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1)
{
    static uint16_t old_x0 = 0xFFFF;
    static uint16_t old_x1 = 0xFFFF;
    static uint16_t old_y0 = 0xFFFF;
    static uint16_t old_y1 = 0xFFFF;
    uint8_t arguments[4];

    if (x0 != old_x0 || x1 != old_x1)
    {
        arguments[0] = (uint8_t)(x0 >> 8);
        arguments[1] = (uint8_t)(x0 & 0xFF);
        arguments[2] = (uint8_t)(x1 >> 8);
        arguments[3] = (uint8_t)(x1 & 0xFF);
        DisplaySendCommandDataArray(DCS_SET_COLUMN_ADDRESS, arguments, 4);
        old_x0 = x0;
        old_x1 = x1;
    }

    if (y0 != old_y0 || y1 != old_y1)
    {
        arguments[0] = (uint8_t)(y0 >> 8);
        arguments[1] = (uint8_t)(y0 & 0xFF);
        arguments[2] = (uint8_t)(y1 >> 8);
        arguments[3] = (uint8_t)(y1 & 0xFF);
        DisplaySendCommandDataArray(DCS_SET_PAGE_ADDRESS, arguments, 4);
        old_y0 = y0;
        old_y1 = y1;
    }
}

void DisplayDriver_DisplayInit(void)
{
    uint8_t arguments[16];

    /* Exit sleep mode FIRST - ST7789 requires this before accepting config */
    DisplaySendCommand(DCS_EXIT_SLEEP_MODE);
    HAL_Delay(120); /* Required delay after sleep-out */

    DisplaySendCommandData(DCS_SET_ADDRESS_MODE, 0x00);
    DisplaySendCommandData(DCS_SET_PIXEL_FORMAT, 0x55);  /* 16bpp RGB565 (both RGB and MCU iface) */
    DisplaySendCommandData(DCS_SET_TEAR_ON, 0x00);
    DisplaySendCommand(DCS_ENTER_INVERT_MODE);

    /* Frame rate / porch setting */
    arguments[0] = 0x0c; arguments[1] = 0x0c; arguments[2] = 0x00;
    arguments[3] = 0x33; arguments[4] = 0x33;
    DisplaySendCommandDataArray(DCS_PORCH_SETTING, arguments, 5);

    DisplaySendCommandData(DCS_GATE_CONTROL, 0x35);

    /* Power setting */
    DisplaySendCommandData(DCS_VCOMS_SETTING,       0x1f);
    DisplaySendCommandData(DCS_LCM_CONTROL,         0x2c);
    DisplaySendCommandData(DCS_VRH_COMMAND_ENABLE,  0x01);
    DisplaySendCommandData(DCS_VRH_SET,             0x12);
    DisplaySendCommandData(0xC4,                    0x20);
    DisplaySendCommandData(DCS_FRAME_RATE_CONTROL,  0x0f);

    arguments[0] = 0xa4; arguments[1] = 0xa1;
    DisplaySendCommandDataArray(DCS_POWER_CONTROL_1, arguments, 2);

    /* Positive gamma */
    arguments[0]  = 0xd0; arguments[1]  = 0x08; arguments[2]  = 0x11;
    arguments[3]  = 0x08; arguments[4]  = 0x0c; arguments[5]  = 0x15;
    arguments[6]  = 0x39; arguments[7]  = 0x33; arguments[8]  = 0x50;
    arguments[9]  = 0x36; arguments[10] = 0x13; arguments[11] = 0x14;
    arguments[12] = 0x29; arguments[13] = 0x2d;
    DisplaySendCommandDataArray(DCS_POSITIVE_GAMMA, arguments, 14);

    /* Negative gamma */
    arguments[0]  = 0xd0; arguments[1]  = 0x08; arguments[2]  = 0x10;
    arguments[3]  = 0x08; arguments[4]  = 0x06; arguments[5]  = 0x06;
    arguments[6]  = 0x39; arguments[7]  = 0x44; arguments[8]  = 0x51;
    arguments[9]  = 0x0b; arguments[10] = 0x16; arguments[11] = 0x14;
    arguments[12] = 0x2f; arguments[13] = 0x31;
    DisplaySendCommandDataArray(DCS_NEGATIVE_GAMMA, arguments, 14);
}

void DisplayDriver_DisplayReset(void)
{
    HAL_GPIO_WritePin(DISP_RST_GPIO_Port, DISP_RST_Pin, GPIO_PIN_RESET);
    HAL_Delay(10);
    HAL_GPIO_WritePin(DISP_RST_GPIO_Port, DISP_RST_Pin, GPIO_PIN_SET);
    HAL_Delay(120); /* Required delay after reset */
}

void DisplayDriver_Init(void)
{
    /* SPI1 is already initialized by MX_SPI1_Init().
     * Nothing extra needed for polling mode (no DMA). */
}

int touchgfxDisplayDriverTransmitActive(void)
{
    return (int)isTransmittingBlock;
}

void touchgfxDisplayDriverTransmitBlock(const uint8_t *pixels, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
{
    isTransmittingBlock = 1;

    Display_Set_Area(x, y, x + w - 1, y + h - 1);

    /* Send RAMWR command */
    HAL_GPIO_WritePin(DISP_CS_GPIO_Port, DISP_CS_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(DISP_DC_GPIO_Port, DISP_DC_Pin, GPIO_PIN_RESET); /* command */
    uint8_t cmd = DCS_WRITE_MEMORY_START;
    HAL_SPI_Transmit(&hspi1, &cmd, 1, HAL_MAX_DELAY);
    HAL_GPIO_WritePin(DISP_DC_GPIO_Port, DISP_DC_Pin, GPIO_PIN_SET);   /* data */

    /*
     * Switch SPI to 16-bit mode so each RGB565 word is sent MSB-first,
     * matching the display's expected byte order.
     * HAL_SPI_Transmit with 16-bit mode treats 'Size' as number of 16-bit words.
     */
    SPI_SetDataWidth16();
    HAL_SPI_Transmit(&hspi1, (uint8_t *)pixels, (uint16_t)(w * h), HAL_MAX_DELAY);
    SPI_SetDataWidth8();

    HAL_GPIO_WritePin(DISP_CS_GPIO_Port, DISP_CS_Pin, GPIO_PIN_SET);

    isTransmittingBlock = 0;
    DisplayDriver_TransferCompleteCallback();
}

void DisplayDriver_DMACallback(void)
{
    /* Not used - project uses polling SPI */
}

int touchgfxDisplayDriverShouldTransferBlock(uint16_t bottom)
{
    (void)bottom;
    /* No tearing effect pin - always allow transfer */
    return 1;
}
